name: Create Zoomin bundle

on:
    workflow_call:
        inputs:
            bundle-name:
                type: string
                required: true

jobs:
    create-zoomin-bundle:
        name: Create Zoomin bundle
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Copy zoomin properties
              run: |
                  cp doc/zoomin/custom.properties doc/ \
                  && cp doc/zoomin/tags.yml doc/

            - name: Create zip file
              run: |
                  cd doc/ \
                  && zip -r "../${{ inputs.bundle-name }}.zip" docs/* mkdocs.yml custom.properties tags.yml

            - name: Upload documentation artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.bundle-name }}
                  path: ${{ inputs.bundle-name }}.zip
                  retention-days: 7
